### ISSUE TITLE
Improve cache support for APIs

### ISSUE THREAD

**Issue by Nana-EC** [hiero-ledger/hiero-json-rpc-relay#1058]
### Problem

The relay support caching for some endpoints and not others. We should assess which would no benefit from it and which may need TTL times updated based on usage

### Solution

Add cache support to heavily utilized methods in which the response does not change.

2025 - MARCh `PLEASE CONDUCT a new review, and design doc in notion. detailing:

- which methods have cache which not, and if yes, the TTL. and if its configurable by config or not
- Distinguish where we cache, at relay level, or close by the MN logic

### Extras

- Group all cache config at our DOC; configuracion sectionm making it understandable, as nowadays it is mixed with other values, and for example MAX_CACHE is only for LRU.
- Group inside cache config, by local and shared cache

_LEGACY_

- [ ] Assess endpoint metrics, what are the heaviest utilized
- [ ] Assess endpoint responses, which are static based on params which do not yet have caching
- [ ] Add caching logic with consideration for mirror node refresh times to ensure details are still fresh
  - [x] #1059
  - [x] #1210
  - [x] #1057  
  - [ ] eth_chainId
  - [ ] eth_feeHistory
  - [ ] net_version
  - [ ] eth_estimateGas
  - [x] #1212
  - [x] eth_getBlockByNumber
  - [x] #1221
- [ ] Permanently cache Earliest block
- [ ] Add cache support for some consensus node calls
  - [x] Add caching logic to getTinyBarGasFee()

**Comment by david-bakin-sl** [comment]
Additionally, perhaps the mirror node could support an event stream (callbacks) that could notify of interesting events that would directly inform cache invalidation.  E.g., new block added.

**Comment by Ferparishuertas** [comment]
A summary ot the pending status of this issue

- We have a full study of which caches we have implemented
- From this baseline we will
-- Remove the etg_getTransaction without lates, or latest cache totally (
-- Review the ttl of all caches
-- Add new ones
-- Refactor where we cache at server level and MN level


Out of scope. Any callback, cleanup mechanics form MN
