### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by victor-yanev** [hiero-ledger/hiero-json-rpc-relay#2689]
### Problem

Some of the logs we do are not giving us enough information and we need more descriptive logs which will give us more context when we are trying to debug any errors that occur in the relay.

### Solution

**TODO:** If you notice a log that can be improved, update the checklist below:

**Fix the following logs to be more descriptive:**
- [ ] [server/src/validator](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/packages/server/src/validator)
  - Change confusing log https://github.com/hashgraph/hedera-json-rpc-relay/blob/a934c3c44d0c9afc36d7471c7dbc63a1e1aaf136/packages/server/src/validator/types.ts#L7
  - Log method name in https://github.com/hashgraph/hedera-json-rpc-relay/blob/a934c3c44d0c9afc36d7471c7dbc63a1e1aaf136/packages/server/src/validator/utils.ts#L33
- [ ] add more items here

**Add missing logs:**
- [ ] add more items here

And open a PR to fix those when we add enough items in the checklist.

**Comment by Ferparishuertas** [comment]
withdrawn
