### ISSUE TITLE
Create a test suite that can be run on mainnet as part of the release process.

### ISSUE THREAD

**Issue by ebadiere** [hiero-ledger/hiero-json-rpc-relay#2944]
### Problem

Currently we run some minor manual tests on mainnet after a release, but executing transactions costs HBar.  

### Solution

A budget to support this effort is being prepared.  A light repeatable test suite that covers basic transactions to act as post release smoke test needs to be developed.   Ideally this will run in CI, currently Github Actions.

- [ ] [Stabilize current tests](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2945)
- [ ] [Define a light test suite for mainnet.](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2946)
- [ ] [Create a CI workflow to run the mainnet acceptance test suite.](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2947)
- [ ] [Create a basic test suite for metamask](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2987)
- [ ] [Add a way to pass or configure balance check before running test suite.](https://github.com/hashgraph/hedera-json-rpc-relay/issues/3007)

### Alternatives

N/A

**Comment by Ferparishuertas** [comment]
This issue after reviewing was discarded, as we have several monitoring alerts, and natural traffic that in case of any error will let us know.
That said all the previous envs tests are key to avoud this kind of issues
